// Senne Bovée — portfolio data, shared across all three directions.
// Keeps copy + project list in one place so we can iterate visuals only.

window.SENNE = {
  name: 'Senne Bovée',
  role: 'Prop Artist & 3D Generalist',
  location: 'Antwerp / Kortrijk, Belgium',
  email: 'bovee.senne@gmail.com',
  phone: '+32 468 24 94 24',
  short: 'Junior prop artist with a generalist\u2019s toolkit. I build the small things that make a world feel lived-in \u2014 then I texture, light and render them until they read.',
  about: 'I\u2019m a final-year Game Graphics Production student at Howest DAE (Kortrijk). Currently a 3D Generalist Intern at Granstudio, where I\u2019m building a procedural city tool for VR car-visibility testing. I love the part of the pipeline where modeling, texturing and lighting meet \u2014 props are where all three have to behave.',
  links: {
    artstation: 'artstation.com/senne_bovee',
    itch: 'senneb.itch.io',
    sketchfab: 'sketchfab.com/bovee.senne',
    eightylv: '80.lv/articles/\u2026/walkie-talkie',
  },
  software: [
    { name: 'Maya', tier: 'daily' },
    { name: 'Blender', tier: 'daily' },
    { name: 'Substance 3D Painter', tier: 'daily' },
    { name: 'ZBrush', tier: 'often' },
    { name: 'Unreal Engine', tier: 'often' },
    { name: 'Photoshop', tier: 'daily' },
    { name: 'Illustrator', tier: 'often' },
    { name: 'Marmoset Toolbag', tier: 'sometimes' },
  ],
  awards: [
    { year: '2024', title: 'DAE Game Projects \u2014 Gamejam Winner', sub: 'Snails & Potions' },
    { year: '2024', title: 'The Rookies \u2014 Rank A', sub: 'Game Development' },
    { year: '2024', title: 'Featured on 80 Level', sub: 'Walkie-Talkie breakdown' },
  ],
  projects: [
    {
      id: 'walkie',
      title: 'Post-Apocalyptic Walkie-Talkie',
      tag: 'Featured on 80 Level',
      year: '2024',
      kind: 'Game Asset \u00b7 AAA pipeline',
      tri: '\u224812k tris',
      software: ['Maya', 'Substance Painter', 'Marmoset'],
      blurb: 'Final piece for the Game Asset Pipeline course at DAE. Took the brief somewhere battered: duct-taped, sun-bleached, with a circuit board peeking through a cracked screen. Built around an AAA workflow \u2014 blockout \u2192 high poly \u2192 retopo \u2192 bake \u2192 PBR texturing.',
      hero: true,
      rarity: 'legendary',
    },
    {
      id: 'snails',
      title: 'Snails & Potions',
      tag: 'Shipped on Steam',
      year: '2024',
      kind: 'Team game \u00b7 Project lead',
      tri: 'Stylised',
      software: ['Maya', 'Substance', 'Unreal'],
      blurb: 'A two-player party game where you sabotage your friend\u2019s snail with potions. Five-person team over six months. I led the project and handled game design, texturing, modeling, rigging and animation. DAE Game Projects 2024 Gamejam Winner; now free on Steam.',
      rarity: 'epic',
    },
    {
      id: 'granstudio',
      title: 'Procedural City for VR',
      tag: 'Internship \u00b7 Granstudio',
      year: '2026',
      kind: 'Tool \u00b7 Houdini / Unreal',
      tri: 'Procedural',
      software: ['Houdini', 'Unreal', 'Python'],
      blurb: 'A procedural city builder with roads and simulated traffic, used to test car visibility in VR. Built as a tool: artists place sliders, not props. Currently in progress.',
      rarity: 'epic',
    },
    {
      id: 'fluvia',
      title: 'Fluvia Fire Escape',
      tag: 'Serious game',
      year: '2025',
      kind: 'Fire safety & awareness',
      tri: 'Stylised',
      software: ['Maya', 'Substance', 'Unreal'],
      blurb: 'Project lead on a serious game that teaches fire-escape protocol. Game design, texturing, modeling, animation and UI all sat with me.',
      rarity: 'rare',
    },
    {
      id: 'saab',
      title: 'MOONFALL ISLAND',
      tag: 'Personal',
      year: '2024',
      kind: 'High-poly vehicle study',
      tri: 'High poly',
      software: ['Maya', 'Substance'],
      blurb: 'A study in clean subdivision modeling. No bake, no shortcuts \u2014 the goal was control edges, fillets and surface continuity. Lit in Marmoset to read as a product render.',
      rarity: 'rare',
    },
    {
      id: 'curator',
      title: 'The Curator of Curiosities',
      tag: 'Stylised character prop',
      year: '2024',
      kind: 'Traveling merchant kit',
      tri: '\u22488k tris',
      software: ['ZBrush', 'Substance', 'Marmoset'],
      blurb: 'A small kit of trinkets a stylised traveling merchant might haul around. An exercise in storytelling through props \u2014 every object had to imply where it came from.',
      rarity: 'rare',
    },
    {
      id: 'gravitag',
      title: 'GraviTag',
      tag: 'Unwrap Gamejam',
      year: '2024',
      kind: 'Gamejam \u00b7 Modeling & UI',
      tri: 'Stylised',
      software: ['Maya', 'Substance', 'Unreal'],
      blurb: 'A gamejam entry built in 48 hours. I handled the 3D modeling and the in-game UI \u2014 fast iteration, hard constraints, no second takes.',
      rarity: 'rare',
    },
  ],
};

// Map of image-slot IDs → file path in assets/work/. Used as the `src=` fallback
// on each <image-slot> so the page ships with images pre-assigned. A user drop
// still overrides this at runtime.
window.WORK_IMAGES = {
  'riso-walkie-bg':     'assets/work/riso-walkie-bg.webp',
  'riso-snails-bg':     'assets/work/riso-snails-bg.webp',
  'riso-snails-fg':     'assets/work/riso-snails-fg.webp',
  'riso-granstudio-fg': 'assets/work/riso-granstudio-fg.webp',
  'riso-fluvia-bg':     'assets/work/riso-fluvia-bg.webp',
  'riso-saab-bg':       'assets/work/riso-saab-bg.webp',
};
window.workImg = (id) => window.WORK_IMAGES[id];
